services:
  - type: web
    name: rimschool
    env: docker
    plan: free
    repo: https://github.com/mounaStart/RimSchool
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
  
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
